var steps = [
    { delay: 2000,  description: "大家好，我叫Ken" },
    { delay: 2500,  description: "又到了区块链学习的时间" },
    { delay: 3300,  description: "今天我们来认识一款非常热门的钱包" },
    { delay: 2500,  description: "Rainbow 钱包" },
    { delay: 5000,  description: "它把以太坊、Layer2（Arbitrum、Optimism等）" },
    { delay: 3000,  description: "体验做得非常好" },
    { delay: 3200,  description: "而且它还有一套积分系统" },
    { delay: 3800,  description: "Rainbow 官方早期有过一些融资" },
    { delay: 4000,  description: "像2022 年拿到了 Union Square Ventures" },
    { delay: 3500,  description: "Seven Seven Six 等机构投资" },
    { delay: 4000,  description: "所以社区里有很多人在猜测未来可能会发币" },
    { delay: 3200,  description: "如果发币并且有空投的话" },
    { delay: 4000,  description: "那积分应该是空投很重要的参考指标" },
    { delay: 4000,  description: "当然了，这只是社区里很多人的猜测" },
    { delay: 3200,  description: "一切以官方公布为准" },
];