var steps = [
    { delay: 2000,  description: "大家好，我叫Ken" },
    { delay: 2500,  description: "又到了区块链学习的时间" },
    { delay: 4000,  description: "今天我们继续学习Defilama中的NFT，解锁，借贷聚合器，中心化交易所透明度，跨链桥，治理，清算水平" },
    { delay: 3800,  description: "本期视频不包含任何投资建议" },
    { delay: 3500,  description: "所有内容仅用于学习和演示" },
    { delay: 4000,  description: "请大家务必根据自己的情况进行判断" },

    { delay: 2500,  description: "我们先来看NFT" },
    { delay: 4000,  description: "点开NFT的菜单栏，可以看到下面有三个子菜单"},
    { delay: 3500,  description: "收藏系列，交易市场和收益" },
    { delay: 2500,  description: "打开收藏系列" },
    { delay: 4000,  description: "可以看到NFT收藏系列的列表" },
    { delay: 6000,  description: "包括名称，地板价格，1天，7天的涨跌幅和交易量，1天的销售量，总供应量和，出售中的数量" },
    { delay: 4000,  description: "点开某个系列，例如胖胖企鹅系列" },

    { delay: 4000,  description: "进入该系列的详细信息页" },
    { delay: 4000,  description: "包括卖价和买价的时间分布图，蓝色的是卖价，绿色的是买价" },
    { delay: 4000,  description: "可以看到当前的卖价集中在10-20ETH之间" },
    { delay: 4000,  description: "而买价不到1ETH" },
    { delay: 4000,  description: "也可以选择包含离群值，可以看到最高的卖价是400ETH" },
    { delay: 4000,  description: "地板价格的走势图" },
    { delay: 4000,  description: "还有订单簿，包含价格和数量的变化" },

    { delay: 4000,  description: "交易市场，可以看到交易折合ETH数量以及交易个数随时间的变化图" },
    { delay: 4000,  description: "可以看到2021年中到2023年初是NFT市场交易的高峰" },
    { delay: 4000,  description: "下面是各个NFT交易所的排名，以及交易量的变化情况，还有市场份额等" },
    { delay: 4000,  description: "第一名是Opensea，第二名是Blur" },

    { delay: 4000,  description: "收益，这里给出了名称，铸造收益，总的版税收益，30天版税收益，和总收益" },

    { delay: 4000,  description: "第二个板块是解锁，首先看总览" },
    { delay: 4000,  description: "总的跟踪协议数量，30天的解锁量10多亿" },
    { delay: 4000,  description: "还有解锁随时间的分布图" },
    { delay: 4000,  description: "可以看到到2028年持续有大量的解锁" },
    { delay: 4000,  description: "还有包括每个币的解锁信息" },
    { delay: 4000,  description: "这里最重要的是总的市值和已解锁的数量占的百分比" },
    { delay: 4000,  description: "我们以川普币为例" },
    { delay: 4000,  description: "它的总量是10亿，目前已解锁了24%" },

    { delay: 4000,  description: "通常情况下由于解锁导致供应量的增加，币的价格会下跌" },
    { delay: 4000,  description: "但是也有例外，比如这个川普币" },
    { delay: 4000,  description: "最近一次解锁的时候是在4月18号，当时价格大概是8USDT左右，目前的价格是13多U，涨了70%" },

    { delay: 4000,  description: "解锁日历" },
    { delay: 4000,  description: "包含哪天哪个币解锁" },
    { delay: 4000,  description: "我们看到四月份量比较大的币是SUI和川普币，解锁后到现在都涨得比较多" },
    
    { delay: 4000,  description: "第三个板块是借贷聚合器，我们先看基础部分" },
    { delay: 4000,  description: "例如我们想借WBTC" },
    { delay: 4000,  description: "以USDT作为抵押物" },
    { delay: 4000,  description: "下面列出了各个平台的年化收益率情况" },
    { delay: 4000,  description: "包括安全和高风险的" },
    { delay: 4000,  description: "有些年化收益率是负数" },
    { delay: 4000,  description: "代表着该平台的流动性不高，所以大家投资要谨慎" },
    { delay: 4000,  description: "接下来是高级部分" },
    { delay: 4000,  description: "可以按照链，借贷协议等过滤搜索" },
    { delay: 4000,  description: "例如我们选择以太坊，AAVE V3" },
    { delay: 4000,  description: "抵押WBTC，借出USDT" },
    { delay: 4000,  description: "最重要的指标是净供应的年化收益率" },
    { delay: 4000,  description: "净借出的年化收益率" },
    { delay: 4000,  description: "还有净年化收益率" },
    { delay: 4000,  description: "正数代表平台给你的利息" },
    { delay: 4000,  description: "负数数代表你付给平台的利息" },

    { delay: 4000,  description: "第四个板块是中心化交易所透明度" },
    { delay: 4000,  description: "这里列出了所有收录的交易所的资产情况和交易量等数据" },
    { delay: 4000,  description: "我们看到前十名都是大家比较熟悉的大的交易所，例如币安，ok等" },

    { delay: 2000,  description: "第五个是跨链桥" },
    { delay: 2000,  description: "我们先看总览" },
    { delay: 3500,  description: "24小时，7天和1个月的交易量" },
    { delay: 3000,  description: "右边是每个具体链的资金流向" },
    { delay: 5000,  description: "资金流入最大的是Arbitrum，流出最大的是Bera" },
    { delay: 5000,  description: "各个跨链桥的交易量" },
    { delay: 5000,  description: "蓝色是是存入，红色的是取出的量" },
    { delay: 5000,  description: "还有各个跨链桥的排名，第一是LayerZero" },
    { delay: 5000,  description: "它们支持的链，各个时间段的交易量和交易个数" },

    { delay: 5000,  description: "也可以按照链来查看" },
    { delay: 5000,  description: "例如从Solana中存入和取出数量，7天净资金流等" },

    { delay: 5000,  description: "交易，这里可以下载各个跨链桥的交易信息" },
    { delay: 5000,  description: "输入开始时间和结束时间，选定桥，点下载" },

    { delay: 2000,  description: "第六个是治理" },
    { delay: 4000,  description: "这里包含每个协议的名称，提案个数，成功的提案数" },
    { delay: 4000,  description: "在过去30天内的提案总数，30天内的提案成功数" },
    { delay: 5000,  description: "DeFiLlama 的 治理部分为用户提供了去中心化治理活动的透明视图" },
    { delay: 5000,  description: "帮助用户了解不同 DAO 的治理动态和社区参与情况" },
    { delay: 5000,  description: "通过这些数据，用户可以更好地评估项目的去中心化程度和社区活跃度" },
    { delay: 3000,  description: "从而做出更适合的决策。" },

    { delay: 3000,  description: "第七个是清算" },
    { delay: 4000,  description: "我们先来简单了解一下清算的逻辑" },
    { delay: 4000,  description: "在 DeFi 借贷协议中" },
    { delay: 5000,  description: "用户通常需要提供加密资产作为抵押品来借款" },
    { delay: 5000,  description: "如果抵押品的价值下降" },
    { delay: 5000,  description: "导致抵押率低于协议设定的最低阈值" },
    { delay: 3000,  description: "系统将自动进行清算" },
    { delay: 4000,  description: "这意味着部分或全部抵押资产将被出售" },
    { delay: 3000,  description: "以偿还借款" },
    { delay: 3000,  description: "防止协议承担坏账风险" },

    { delay: 3000,  description: "我们现在右上角选择资产" },
    { delay: 3000,  description: "例如WBTC，它对标的是比特币BTC" },
    { delay: 3000,  description: "左边列出了待清算的资产价值" },
    { delay: 3000,  description: "在右边的图里看到在8万和6万左右Compound协议里都有一个比较大的清算" },
    { delay: 3000,  description: "但是集中的清算区域在8000-30000左右" },

    { delay: 3000,  description: "下面是清算列表，包括协议，链，地址，币的价值和数量，还有清算价格" },
    { delay: 3000,  description: "在Compound中，61,181的时候有412个WBTC要清算， 80,550的时候有272个" },

    { delay: 3000,  description: "好了，以上就是本期视频的全部内容" },
    { delay: 2000,  description: "如果大家对视频感兴趣" },
    { delay: 2000,  description: "欢迎订阅我的频道" },
    { delay: 3000,  description: "也可以在评论区告诉我你的想法" },
    { delay: 2000,  description: "谢谢大家" }    
];
